language: php

php:
  - 5.3

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --configuration test/phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  # Add -v flag to enable logging
  - php vendor/bin/coveralls

notifications:
  email: false
