language: php

php:
  - 5.3

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --configuration test/phpunit-travis.xml --coverage-clover build/logs/clover.xml

notifications:
  email: false
