<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DesignmovesStrictViewVars\Module'                                           => __DIR__ . '/Module.php',
  'DesignmovesStrictViewVars\Factory\Listener\ViewModelListenerFactory'        => __DIR__ . '/src/DesignmovesStrictViewVars/Factory/Listener/ViewModelListenerFactory.php',
  'DesignmovesStrictViewVars\Factory\Options\ModuleOptionsFactory'             => __DIR__ . '/src/DesignmovesStrictViewVars/Factory/Options/ModuleOptionsFactory.php',
  'DesignmovesStrictViewVars\Factory\View\Renderer\PhpRendererFactory'         => __DIR__ . '/src/DesignmovesStrictViewVars/Factory/View/Renderer/PhpRendererFactory.php',
  'DesignmovesStrictViewVars\Initializer\ViewHelperInitializer'                => __DIR__ . '/src/DesignmovesStrictViewVars/Initializer/ViewHelperInitializer.php',
  'DesignmovesStrictViewVars\Listener\ViewModelListener'                       => __DIR__ . '/src/DesignmovesStrictViewVars/Listener/ViewModelListener.php',
  'DesignmovesStrictViewVars\Options\ModuleOptions'                            => __DIR__ . '/src/DesignmovesStrictViewVars/Options/ModuleOptions.php',
  'DesignmovesStrictViewVars\View\Renderer\PhpRenderer'                        => __DIR__ . '/src/DesignmovesStrictViewVars/View/Renderer/PhpRenderer.php',
  'DesignmovesStrictViewVarsTest\Bootstrap'                                    => __DIR__ . '/test/Bootstrap.php',
  'DesignmovesStrictViewVarsTest\Factory\Listener\PageListenerFactoryTest'     => __DIR__ . '/test/DesignmovesStrictViewVarsTest/Factory/Listener/ViewModelListenerFactoryTest.php',
  'DesignmovesStrictViewVarsTest\Factory\Options\ModuleOptionsFactoryTest'     => __DIR__ . '/test/DesignmovesStrictViewVarsTest/Factory/Options/ModuleOptionsFactoryTest.php',
  'DesignmovesStrictViewVarsTest\Factory\View\Renderer\PageServiceFactoryTest' => __DIR__ . '/test/DesignmovesStrictViewVarsTest/Factory/View/Renderer/PhpRendererFactoryTest.php',
  'DesignmovesStrictViewVarsTest\Initializer\ViewHelperInitializerTest'        => __DIR__ . '/test/DesignmovesStrictViewVarsTest/Initializer/ViewHelperInitializerTest.php',
  'DesignmovesStrictViewVarsTest\Listener\ViewModelListenerTest'               => __DIR__ . '/test/DesignmovesStrictViewVarsTest/Listener/ViewModelListenerTest.php',
  'DesignmovesStrictViewVarsTest\Options\ModuleOptionsTest'                    => __DIR__ . '/test/DesignmovesStrictViewVarsTest/Options/ModuleOptionsTest.php',
  'DesignmovesStrictViewVarsTest\View\Renderer\PhpRendererTest'                => __DIR__ . '/test/DesignmovesStrictViewVarsTest/View/Renderer/PhpRendererTest.php',
);
